name: Docs

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - ".github/workflows/docs.yml"
  workflow_dispatch:

jobs:
  docs:
    uses: MrThearMan/CI/.github/workflows/docs.yml@v0.3.1
    with:
      os: "windows-latest"
