name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - "**.py"
      - "pyproject.toml"
      - "poetry.lock"
      - ".github/workflows/test.yml"
  workflow_dispatch:

jobs:
  test:
    uses: MrThearMan/CI/.github/workflows/test.yml@v0.3.1
    with:
      os: '["windows-latest"]'
      submit-os: "windows-latest"
      poetry-version: "1.5.1"
      python-version: '["3.8", "3.9", "3.10", "3.11"]'
